version: '3.8'

services:
  evraz-tg-bot:
    hostname: evraz-tg-bot
    container_name: evraz-tg-bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${EVRAZ_TG_BOT_PORT:-8010}:${EVRAZ_TG_BOT_PORT:-8010}"
    volumes:
      - ./data:/app/data
    networks:
      - mutagen-evraz-backend

networks:
  mutagen-evraz-backend:
    external: true
    name: mutagen-evraz-backend